### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [otakuto/gentoo-build-server#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by otakuto** [comment]
Thank you.
It is unused...
I remove It.

**Comment by dtolnay** [comment]
Thanks! You will need to remove it from Cargo.toml as well.
